kind: pipeline
type: docker
name: charts-ci

steps:

- name: validate_chart
  image: alpine/helm:3.2.4
  commands:
    - ./ci/test.sh
  when:
    branch: master
    event: [push, tag, pull_request]

- name: build_latest_chart
  image: alpine/helm:3.2.4
  commands:
    - export VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))-$(git rev-parse --short HEAD)
    - ./ci/build.sh $VERSION unstable
  when:
    branch: master
    event: push

- name: build_release_chart
  image: alpine/helm:3.2.4
  commands:
    - ./ci/build.sh ${DRONE_TAG}
  when:
    branch: master
    event: tag

- name: upload
  image: plugins/s3
  settings:
    endpoint:
      from_secret: s3_endpoint
    region:
      from_secret: s3_region
    bucket:
      from_secret: s3_bucket
    access_key:
      from_secret: s3_access_key
    secret_key:
      from_secret: s3_secret_key
    source: output/**/*
    strip_prefix: output/
    target: /
    acl: public-read
  when:
    branch: master
    event: [push, tag]
